### ISSUE TITLE
[BUG] p & ul text colour in timeline component differs 

### ISSUE THREAD

**Issue by dcollett** [unimelb/design-system-issues#25]
When using a timeliine component, ul text colour is #66666 but p text colour is the body default of #272727

## Expected behaviour
Text will be a consistent colour when using either p  or ul

## Steps to reproduce
See https://le.unimelb.edu.au/new-lms#jump5

![Screen Shot 2019-11-14 at 1 00 15 pm](https://user-images.githubusercontent.com/1088483/68820438-5878b200-06df-11ea-8f3e-fc7aaba68ad8.png)

### Affected browsers

- [x] Chrome 78
- [x] Firefox 71
- [ ] Edge
- [ ] IE 11
- [ ] Safari 8+
- [ ] iOS 8.4+
- [ ] Android 4.4+

## Possible solution
.uomcontent .timeline p {
    color: #666;
}

**Comment by tomstringer** [comment]
Also, should those dates be sentence-cased @jaredh-um ?

**Comment by jaredh-um** [comment]
Hi @makenosound 

- [ ] Adjust `.uomcontent .timeline ul li` to use standard body `p` colour #272727
- [ ] Remove `text-transform: uppercase` from `.uomcontent .timeline dt`

**Comment by tomstringer** [comment]
Resolved with unimelb/Gen3#125

**Comment by dcollett** [comment]
The text colour is still not right - see: https://le.unimelb.edu.au/new-lms/_nocache#jump5

**Comment by tomstringer** [comment]
@dcollett You've got a local style in there overriding the design system.

![Screen Shot 2019-12-11 at 1 28 47 pm](https://user-images.githubusercontent.com/924501/70586061-3dd02500-1c1a-11ea-829f-92b610979b31.png)

**Comment by dcollett** [comment]
Ooops, should’ve looked closer. Thanks Tom.
